# SPDX-FileCopyrightText: 2021 Jonathan Underwood <junderwood@bitcoinbank.co.jp>
#
# SPDX-License-Identifier: AGPL-3.0-only

# yaml-language-server: $schema=../../app-standard-v1.json

version: 1
metadata:
  category: Password Managers
  name: Vaultwarden
  version: 1.25.1
  tagline: Unofficial Bitwarden® compatible server
  description: >-
    Vaultwarden (formerly known as Bitwarden_RS) is an alternative
    implementation\ of the Bitwarden® server API written in Rust, compatible
    with upstream BitwardenÂ®\ clients*. Vaultwarden is perfect for self-hosting
    all of your passwords in an\ encrypted vault on your Citadel. Vaultwarden is
    a full implementation of BitwardenÂ®\ API that includes:

    - Organizations support

    - Attachments

    - Vault API support

    - Serving the static files for Vault interface

    - Website icons API

    - Authenticator and U2F support

    - YubiKey and Duo support


    Please note that Vaultwarden is not associated with the Bitwarden® project nor 8bit Solutions LLC. When using this app, please report any bugs or suggestions to us directly, regardless of whatever clients you are using (mobile, desktop, browser, etc), and do not use Bitwarden®'s official support channels.
  developer: Daniel García
  website: https://github.com/dani-garcia
  dependencies: []
  repo: https://github.com/dani-garcia/vaultwarden
  support: https://vaultwarden.discourse.group/
  gallery:
    - 1.jpg
    - 2.jpg
    - 3.jpg
  torOnly: true
containers:
  - image: vaultwarden/server:1.25.1@sha256:09b7c56d8224e5d6ecd1a0d940aba658cab5ed4f3f89ca92a4bc7a1edde4b8d3
    user: 1000:1000
    port: 3000
    environment:
      ROCKET_PORT: 3000
    name: server
    data:
      - data:/data
