# SPDX-FileCopyrightText: 2022 Citadel and contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# yaml-language-server: $schema=../../app-standard-v1.json

version: 1
metadata:
  category: Social
  name: Synapse
  version: 1.61.0
  tagline: Matrix homeserver
  description: Description is coming soon.
  developer: Matrix
  website: https://matrix.org
  dependencies: []
  repo: https://github.com/matrix-org/synapse
  support: https://matrix.to/#/#synapse:matrix.org
  gallery:
    - 1.jpg
    - 2.jpg
    - 3.jpg
  torOnly: false
containers:
  - image: matrixdotorg/synapse:v1.61.0@sha256:2ebcc1d9d1083af980cc2f4ed7528affbc573e3064cc464a0110abb152dcac9e
    entrypoint: bash
    command: -c './start.py generate && ./start.py migrate_config && exec ./start.py'
    environment:
      UID: "1000"
      GID: "1000"
      SYNAPSE_HTTP_PORT: ${APP_SYNAPSE_SERVER_PORT}
      SYNAPSE_SERVER_NAME: ${APP_HIDDEN_SERVICE}
      SYNAPSE_REPORT_STATS: yes
      SYNAPSE_ENABLE_REGISTRATION: yes
      SYNAPSE_NO_TLS: yes
    name: server
    data:
      - data/synapse:/data
