
version: 1
metadata:
  category: Networking
  name: Uptime Kuma
  version: 1.17.0
  tagline: Self-hosted uptime monitoring tool
  description: >
    Uptime Kuma is a self-hosted monitoring tool like Uptime Robot.


    Features:


    - Monitoring uptime for HTTP(s) / TCP / HTTP(s) Keyword / Ping / DNS Record / Push / Steam Game Server.

    - Fancy, Reactive, Fast UI/UX.

    - Notifications via Telegram, Discord, Gotify, Slack, Pushover, Email (SMTP), and 70+ notification services.

    - 20 second intervals.

    - Multi Languages

    - Simple Status Page

    - Ping Chart

    - Certificate Info
  developer: Louis Lam
  website: https://uptime.kuma.pet
  dependencies: []
  repo: https://github.com/louislam/uptime-kuma
  support: https://github.com/louislam/uptime-kuma/issues
  gallery:
    - 1.jpg
    - 2.jpg
    - 3.jpg
containers:
  - name: main
    image: louislam/uptime-kuma:1.17.0@sha256:080b34c0953f7f324731439c5e8000902d21622a44f7f01215aacbeaf741a30c
    restart: on-failure
    stop_grace_period: 1m
    port: 3001
    data:
      - data:/app/data
